---
  - name: Install Nginx (Debian/Ubuntu)
    apt:
      name: nginx
      state: present
    when: ansible_os_family == 'Debian'
  - name: Start and enable Nginx service
    service:
      name: nginx
      state: started
      enabled: yes