---
  - name: Install required packages
    apt:
      name:
        - unzip
        - openjdk-17-jdk
      state: present
      update_cache: yes

  - name: Set Java 17 as default
    shell: |
      update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

  - name: Copy Keycloak zip file
    copy:
      src: keyclock.zip
      dest: /tmp/keycloak-21.1.2.zip
      mode: "0755"

  - name: Copy Certificates
    copy:
      src: certificates/
      dest: /etc/ssl/
      mode: "0755"

  - name: Unzip Keycloak
    unarchive:
      src: /tmp/keycloak-21.1.2.zip
      dest: /root/
      remote_src: yes

  - name: Create systemd service file for Keycloak
    copy:
      dest: /etc/systemd/system/keycloak.service
      content: |
          [Unit]
          Description=Keycloak Service
          After=network.target

          [Service]
          Type=simple
          User=root
          ExecStart=/root/keycloak-21.1.2/bin/kc.sh start-dev
          Restart=on-failure
          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          Environment=KEYCLOAK_ADMIN=admin
          Environment=KEYCLOAK_ADMIN_PASSWORD=admin

          [Install]
          WantedBy=multi-user.target

  - name: Reload systemd
    systemd:
      daemon_reload: yes

  - name: Set Keycloak configuration
    lineinfile:
      path: /root/keycloak-21.1.2/conf/keycloak.conf
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
      create: yes
      mode: '0644'
    loop: "{{ keycloak_config }}"

  - name: Enable and start Keycloak
    systemd:
      name: keycloak
      enabled: yes
      state: started
