bpm_install_dir: "./file/newBpm.zip"
keycloakcrt: "keyclock.crt.pem"
keycloackip: "{{ hostvars['keyclock']['ansible_host'] }}"
OpenKMip: "{{ hostvars['openkm']['ansible_host'] }}"
activemqip: "{{ hostvars['activemq']['ansible_host'] }}"
java_version: "11.0.15"
java_build: "10"
java_major: "11"
java_archive_name: "OpenJDK{{ java_major }}U-jdk_x64_linux_hotspot_{{ java_version }}_{{ java_build }}.tar.gz"
java_download_url: "https://github.com/adoptium/temurin{{ java_major }}-binaries/releases/download/jdk-{{ java_version }}%2B{{ java_build }}/{{ java_archive_name }}"
java_install_dir: "/opt/"
java_extract_path: "{{ java_install_dir }}/jdk-{{ java_version }}"
openkm_url: "http://localhost:8989/OpenKM"
activemq_logq: "logQ"
activemq_url: "tcp://localhost:61616"
activemq_user: "admin"
activemq_pass: "admin"
activemq_queue: "testQ"
localization_url: "http://localhost:8090"
