---
- name: BPM Playbook
  hosts: bpm_servers
  become: true
  vars:
    bpm_install_dir: "./newBpm"
    keycloakcrt: "keyclock.crt.pem"
    keycloackip: "{{ hostvars['keyclock']['ansible_host'] }}"
    OpenKMip: "{{ hostvars['openkm']['ansible_host'] }}"
    activemqip: "{{ hostvars['activemq']['ansible_host'] }}"
    java_version: "11.0.15"
    java_build: "10"
    java_major: "11"
    java_archive_name: "OpenJDK{{ java_major }}U-jdk_x64_linux_hotspot_{{ java_version }}_{{ java_build }}.tar.gz"
    java_download_url: "https://github.com/adoptium/temurin{{ java_major }}-binaries/releases/download/jdk-{{ java_version }}%2B{{ java_build }}/{{ java_archive_name }}"
    java_install_dir: "/opt/"
    java_extract_path: "{{ java_install_dir }}/jdk-{{ java_version }}"
  tasks:
    - name: Install Java verion 11.0.15 jdk 
      file:
        path: "{{ java_install_dir }}"
        state: directory
    - name: Download Java archive
      get_url:
        url: "{{ java_download_url }}"
        dest: "/tmp/{{ java_archive_name }}"   

    - name: Extract Java
      unarchive:
        src: "/tmp/{{ java_archive_name }}"
        dest: "{{ java_install_dir }}"
        remote_src: yes
    - name: copy the bpm from the local machine to the remote server
      copy:
        src: "{{ bpm_install_dir }}"
        dest: "/root/"
        mode: "0755"
